name: CI

on:
  push:
    branches:
      - main
  pull_request: {}

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-test:
    name: Lint • Format • Build • Test • Coverage (Node ${{ matrix.node-version }})
    runs-on: ubuntu-latest
    env:
      CI: true
    strategy:
      fail-fast: false
      matrix:
        node-version:
          - 22.x
          - 24.x

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Setup Node
        uses: actions/setup-node@v5
        with:
          node-version: ${{ matrix.node-version }}
          cache: pnpm

      - name: Install
        run: pnpm install --frozen-lockfile

      - name: Lint
        run: pnpm lint:check

      - name: Format
        run: pnpm format:check

      - name: Build
        run: pnpm build

      - name: Test • Coverage
        run: pnpm coverage

      - name: Upload htms-js coverage
        uses: codecov/codecov-action@v5
        with:
          name: htms-js
          flags: htms-js
          files: ./packages/htms-js/coverage/lcov.info
          fail_ci_if_error: true

      - name: Upload fastify-htms coverage
        uses: codecov/codecov-action@v5
        with:
          name: fastify-htms
          flags: fastify-htms
          files: ./packages/fastify-htms/coverage/lcov.info
          fail_ci_if_error: true

      - name: Upload htms-server coverage
        uses: codecov/codecov-action@v5
        with:
          name: htms-server
          flags: htms-server
          files: ./packages/htms-server/coverage/lcov.info
          fail_ci_if_error: true
