on:
  workflow_run:
    workflows:
      - CI
    types:
      - completed

permissions:
  issues: write
  contents: write
  pull-requests: write

name: RELEASE

jobs:
  release-please:
    if: github.event.workflow_run.conclusion == 'success' &&
      github.event.workflow_run.event == 'push' &&
      github.event.workflow_run.head_branch == 'main'
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@v4
        with:
          token: ${{ secrets.RELEASE_PLEASE_TOKEN }}
